export const refs = {
  moviesContainer: document.querySelector('.movies__list'),
  // genresList: document.querySelector('.genres__list'),
  // switchBtn: document.querySelector('.switch-btn'),
  // switchBtnToggle: document.querySelector('.switch-btn::after'),
  body: document.querySelector('body'),
  card: document.querySelector('.gallery__card'),
  header: document.querySelector('.header'),
  pageHome: document.querySelector('#home'),
  pageLibrary: document.querySelector('#library'),
  form: document.querySelector('.header__wrap--form'),
  btnLibrary: document.querySelector('.header__wrap--btn'),
  headerWrap: document.querySelector('.header__wrap'),
  openOurTeam: document.querySelector('.footer__open-modal'),
  libraryButtonsBlock: document.querySelector('.js-library-buttons-wrap'),
  buttonLibraryWatched: document.querySelector('.js-watched'),
  buttonLibraryQueue: document.querySelector('.js-queue'),
  pagination: document.querySelector('.js-paginator'),
};
